---
- name: Config mypc
  hosts: localhost
  become: yes
  tasks:

   - name: apt update
     apt:
           update_cache: yes 

   - name: apt upgrade
     apt:
           upgrade: 'True' 


   - name: install apt packages
     package:
       state: present
       name:
         - kolourpaint
         - pdfarranger
         - vim
         - cheese
         - rapid-photo-downloader
         - shotwell
         - htop
         - blastem
         - zsnes

   - name: install snap packages
     snap:
       state: present 
       name: 
         - discord
         - gimp
         - inkscape
         - qr-code-generator-desktop
         - spotify
         - vlc
         - libreoffice
         - remmina

   - name: install slack|vscode
     snap:
       state: present 
       classic: yes
       name: 
         - slack
         - vscode

   - name: add chrome gpg-key
     apt_key:
            url: https://dl.google.com/linux/linux_signing_key.pub
            state: present

   - name: add chrome repository
     apt_repository:
            repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
            state: present
            update_cache: yes

   - name: install chrome
     package:
       state: present
       name:
         - google-chrome-stable

   - name: add virtualbox gpg-key
     apt_key:
            url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
            state: present

   - name: add virtualbox gpg-key
     apt_key:
            url: https://www.virtualbox.org/download/oracle_vbox.asc
            state: present

   - name: add virtualbox repository
     apt_repository:
            repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
            state: present
            update_cache: yes

   - name: install virtual box
     package:
       state: present
       name:
         - virtualbox-6.1

   - name: add groups your_user|vboxusers
     user:
       name: guilherme 
       groups: vboxusers 
       append: yes 

   - name: meet the prerequisites docker 
     package:
       state: present
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common

   - name: add docker gpg-key
     apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

   - name: add docker repository
     apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update_cache: yes

   - name: install docker 
     package:
       state: present
       name:
         - docker-ce
         - docker-ce-cli
         - containerd.io

